# Generated by Django 2.2.16 on 2021-12-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20211130_1808'),
        ('reviews', '0003_auto_20211202_0822'),
    ]

    operations = [
    ]
