# Generated by Django 2.2.16 on 2021-12-03 12:11

from django.db import migrations, models
import reviews.enums


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_merge_20211203_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(choices=[(10, 10), (9, 9), (8, 8), (7, 7), (6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('moderator', 'moderator'), ('admin', 'admin')], default=reviews.enums.Roles('user'), max_length=9, null=True),
        ),
    ]
